services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: care_ems
      POSTGRES_PASSWORD: care_ems
      POSTGRES_DB: care_ems
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: