spring.application.name=CARE-EMS-API

spring.datasource.url=jdbc:postgresql://localhost:5432/care_ems
spring.datasource.username=care_ems
spring.datasource.password=care_ems
spring.datasource.driver-class-name=org.postgresql.Driver